### ISSUE TITLE
Magento 2.4.3 invalidates normal customer session when GraphQL token is used

### ISSUE THREAD

**Issue by jissereitsma** [hyva-themes/magento2-graphql-tokens#9]
After upgrading to Magento 2.4.3, I'm suffering from the following issue: If I login into the Magento frontend (Hyva or Luma) using the regular customer login, this `Hyva_GraphqlTokens` module adds a `signin_token` to the `customer` customerData section (which can easily be replayed by a GET of `http://magento/customer/section/load/?sections=customer`. However, once I make a GraphQL query or mutation with the `Authentication: Bearer TOKEN` set (like the following GraphQL query via Altair), the customer session is ended and therefore the customer section data is empty again.

```graphql
query {
    customer {
      firstname
    }
}
``` 

This does not seem to be an issue caused by this module. However, I think that this will definitely cause issues with Hyva because of the combination between traditional frontend rendering and GraphQL. 

(Still diving deeper into this.)

**Comment by jissereitsma** [comment]
Alright, that was an easy find: There is a new plugin `\Magento\CustomerGraphQl\Plugin\ClearCustomerSessionAfterRequest` that causes this behaviour. With a file `etc/graphql/di.xml` this is easily fixed (by disabling the original plugin): 
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\GraphQl\Controller\GraphQl">
        <plugin name="ClearCustomerSessionAfterRequest" type="Magento\CustomerGraphQl\Plugin\ClearCustomerSessionAfterRequest" sortOrder="1" disabled="true" />
    </type>
</config>
```

But I'm not sure how much of a security thread, this plugin is actually supposed to fix ....

**Comment by michalbiarda** [comment]
@jissereitsma I believe that this was added to force headless apps using Magento GQL API to be stateless. In our (monolith Hyva) case such cleanup is not needed, because we are stateful. IMO, we could disable this plugin in `Hyva_Theme` module.

**Comment by jissereitsma** [comment]
I think the exact same thing. PR is here https://github.com/hyva-themes/magento2-graphql-tokens/pull/10

**Comment by wigman** [comment]
Thank you @jissereitsma and @michalbiarda !

**Comment by Vinai** [comment]
Has one of you by chance dug up the PR that added the plugin to Magento core?
I would like to read any records about the decision process.

**Comment by jissereitsma** [comment]
Nope, did not dive into this yet.

**Comment by jissereitsma** [comment]
https://github.com/magento/magento2/commit/937a3e2d16183c3e9dd9220ce383e578a2dff50e#diff-9ae123270851537d314f552654ccecf67f9c03c54bcd7e439acfdd15cc2c1635

**Comment by Vinai** [comment]
Thanks, I found the commit, too, but I didn't find any additional information about why the plugin was added.
